module.exports = {
	fault: [
		{ "code": 3, "name": "Estop/Door", "jam": 2 },
		{ "code": 5, "name": "Estop/Door", "jam": 2 },
		{ "code": 6, "name": "Estop/Door", "jam": 2 },
		{ "code": 7, "name": "Estop/Door", "jam": 2 },
		{ "code": 8, "name": "Estop/Door", "jam": 2 },
		{ "code": 9, "name": "Estop/Door", "jam": 2 },
		{ "code": 10, "name": "Estop/Door", "jam": 2 },
		{ "code": 11, "name": "Estop/Door", "jam": 2 },
		{ "code": 12, "name": "Estop/Door", "jam": 2 },
		{ "code": 13, "name": "Estop/Door", "jam": 2 },
		{ "code": 14, "name": "Estop/Door", "jam": 2 },
		{ "code": 15, "name": "Estop/Door", "jam": 2 },
		{ "code": 16, "name": "Estop/Door", "jam": 2 },
		{ "code": 17, "name": "Fault", "jam": 0 },
		{ "code": 18, "name": "Fault", "jam": 0 },
		{ "code": 19, "name": "Lo Air Pressure", "jam": 0 },
		{ "code": 20, "name": "Fault", "jam": 0 },
		{ "code": 21, "name": "Fault", "jam": 0 },
		{ "code": 22, "name": "Fault", "jam": 0 },
		{ "code": 23, "name": "Fault", "jam": 0 },
		{ "code": 24, "name": "Fault", "jam": 0 },
		{ "code": 25, "name": "Lo Air Pressure", "jam": 0 },
		{ "code": 26, "name": "Fault", "jam": 0 },
		{ "code": 27, "name": "Fault", "jam": 0 },
		{ "code": 28, "name": "Fault", "jam": 0 },
		{ "code": 29, "name": "Fault", "jam": 0 },
		{ "code": 171, "name": "Feeder Servo Fault", "jam": 1 },
		{ "code": 175, "name": "Feeder Spreader Home Failure", "jam": 1 },
		{ "code": 114, "name": "Feeder Estop", "jam": 2 },
		{ "code": 124, "name": "Feeder Estop/Reset", "jam": 2 },
		{ "code": 151, "name": "Feeder Transverse Left Drive ", "jam": 1 },
		{ "code": 161, "name": "Feeder Transverse Right Drive", "jam": 1 },
		{ "code": 184, "name": "Feeder Rollmotor Fault Center", "jam": 1 },
		{ "code": 185, "name": "Feeder Center Inlet Sensor ", "jam": 1 },
		{ "code": 186, "name": "Feeder Center Inlet Left Array  ", "jam": 1 },
		{ "code": 187, "name": "Feeder Center Inlet Right Array ", "jam": 1 },
		{ "code": 188, "name": "Feeder Center Inlet Left RollSensor", "jam": 1 },
		{ "code": 189, "name": "Feeder Center Inlet Right RollSensor", "jam": 1 },
		{ "code": 134, "name": "Feeder Rollmotor Fault Left", "jam": 1 },
		{ "code": 135, "name": "Feeder Left Inlet Sensor ", "jam": 1 },
		{ "code": 136, "name": "Feeder Left Inlet Left Array  ", "jam": 1 },
		{ "code": 137, "name": "Feeder Left Inlet Right Array  ", "jam": 1 },
		{ "code": 138, "name": "Feeder Left Inlet Left RollSensor", "jam": 1 },
		{ "code": 139, "name": "Feeder Left Inlet Right RollSensor", "jam": 1 },
		{ "code": 144, "name": "Feeder Rollmotor Fault Right", "jam": 1 },
		{ "code": 145, "name": "Feeder Right Inlet Sensor ", "jam": 1 },
		{ "code": 146, "name": "Feeder Right Inlet Left Array  ", "jam": 1 },
		{ "code": 147, "name": "Feeder Right Inlet Right Array  ", "jam": 1 },
		{ "code": 148, "name": "Feeder Right Inlet Left RollSensor", "jam": 1 },
		{ "code": 149, "name": "Feeder Right Inlet Right RollSensor", "jam": 1 },
		{ "code": 112, "name": "Feeder Estop", "jam": 2 },
		{ "code": 113, "name": "Feeder Estop", "jam": 2 },
		{ "code": 130, "name": "Inverter Fault Ironer", "jam": 2 },
		{ "code": 122, "name": "Feeder Estop Reset", "jam": 2 },
		{ "code": 125, "name": "Inverter Fault Feeder", "jam": 1 },
		{ "code": 155, "name": "Feeder Left Transverse Sensor Fault", "jam": 1 },
		{ "code": 165, "name": "Feeder Right Transverse Sensor Fault", "jam": 1 }
		]
}