module.exports = {
	item: [
		{ number: 1, name: 'Sheets', standard: parseInt(350), area: parseInt(0), department: 'sheets', weight: null, active: true },
		{ number: 2, name: 'Bath Towels', standard: parseInt(900), area: parseInt(0), department: 'towels', weight: null, active: true },
		{ number: 3, name: 'Baby Blankets', standard: parseInt(800), area: parseInt(0), department: 'blankets', weight: null, active: true },
		{ number: 4, name: 'IV Gowns', standard: parseInt(475), area: parseInt(0), department: 'misc', weight: null, active: true },
		{ number: 5, name: 'Fitted Sheets', standard: parseInt(350), area: parseInt(0), department: 'sheets', weight: null, active: true },
		{ number: 6, name: 'IC Pads', standard: parseInt(550), area: parseInt(0), department: 'misc', weight: null, active: true },
		{ number: 7, name: 'Bath Blankets', standard: parseInt(450), area: parseInt(0), department: 'blankets', weight: null, active: true },
		{ number: 8, name: 'Pillowcases', standard: parseInt(700), area: parseInt(0), department: 'misc', weight: null, active: true },
		{ number: 9, name: 'OR Towels', standard: parseInt(700), area: parseInt(0), department: 'towels', weight: null, active: true },
		{ number: 10, name: 'Wash Cloth- Hand Fold', standard: parseInt(1500), area: parseInt(0), department: 'towels', weight: null, active: true },
		{ number: 11, name: 'OR Pants', standard: parseInt(275), area: parseInt(0), department: 'misc', weight: null, active: true },
		{ number: 12, name: 'OR Shirts', standard: parseInt(350), area: parseInt(0), department: 'misc', weight: null, active: true },
		{ number: 13, name: 'Hand Towel', standard: parseInt(800), area: parseInt(0), department: 'towels', weight: null, active: true },
		]
    /*item: [
        { number: 1, name: 'Incontinent Pad', standard: parseInt(720), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 2, name: 'Bath Mat', standard: parseInt(720), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 3, name: 'Patient Gown', standard: parseInt(400), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 4, name: 'Pool Towel', standard: parseInt(625), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 5, name: 'Bath Towel', standard: parseInt(625), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 6, name: 'Hand Towel', standard: parseInt(625), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 7, name: 'Bath Towel (1Primary)', standard: parseInt(625), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 8, name: 'Hand Towel (1Primary)', standard: parseInt(625), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 9, name: 'Bib White (Sideway)', standard: parseInt(625), area: parseInt(1), department: 'Hand Work', weight: null, active: true },
        { number: 10, name: 'Bib color (Longway)', standard: parseInt(625), area: parseInt(1), department: 'Hand Work', weight: null, active: true },
        { number: 11, name: 'Bib color (Small)', standard: parseInt(600), area: parseInt(15), department: 'Hand Work', weight: null, active: true },
        { number: 12, name: 'Patient Gown XL Grand', standard: parseInt(360), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 13, name: 'Thermal Blanket', standard: parseInt(480), area: parseInt(1), department: 'Blankets', weight: null, active: true },
        { number: 14, name: 'Bath Sheet', standard: parseInt(600), area: parseInt(1), department: 'Sheets', weight: null, active: true },
        { number: 15, name: 'Bath Blanket', standard: parseInt(480), area: parseInt(1), department: 'Blankets', weight: null, active: true },
        { number: 16, name: 'Towel (1Primary)', standard: parseInt(625), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 17, name: 'Blankets', standard: parseInt(480), area: parseInt(1), department: 'Blankets', weight: null, active: true },
        { number: 18, name: 'Pads', standard: parseInt(720), area: parseInt(1), department: 'Hand Work', weight: null, active: true },
        { number: 19, name: 'Fitted Sheets', standard: parseInt(360), area: parseInt(2), department: 'Sheets', weight: null, active: true },
        { number: 21, name: 'Quilted Blanket', standard: parseInt(300), area: parseInt(1), department: 'Blankets', weight: null, active: true },
        { number: 20, name: 'Fitted Sheets Large', standard: parseInt(300), area: parseInt(1), department: 'Sheets', weight: null, active: true },
        { number: 22, name: 'Knitted Fitted (offset L)', standard: parseInt(330), area: parseInt(1), department: 'Sheets', weight: null, active: true },
        { number: 23, name: 'WashCloth', standard: parseInt(1425), area: parseInt(1), department: 'Hand Work', weight: null, active: true },
        { number: 24, name: 'BarMop', standard: parseInt(1380), area: parseInt(1), department: 'Misc', weight: null, active: true },
        { number: 25, name: 'Knitted Fitted', standard: parseInt(330), area: parseInt(1), department: 'Sheets', weight: null, active: true },
        { number: 26, name: 'HospitalSheet', standard: parseInt(375), area: parseInt(2), department: 'Sheets', weight: null, active: true },
        { number: 27, name: 'Table Linen', standard: parseInt(300), area: parseInt(2), department: 'Table Tops', weight: null, active: true },
        { number: 28, name: 'Wash Cloth', standard: parseInt(1380), area: parseInt(1), department: 'Hand Work', weight: null, active: true },
        { number: 29, name: 'Hotel Sheet', standard: parseInt(420), area: parseInt(2), department: 'Sheets', weight: null, active: true },
        { number: 30, name: 'Large Thermal Blanket', standard: parseInt(480), area: parseInt(2), department: 'Blankets', weight: null, active: true },
        { number: 31, name: 'Large Blanket', standard: parseInt(480), area: parseInt(2), department: 'Blankets', weight: null, active: true },
        { number: 0, name: 'Needs To Be Added ', standard: parseInt(750), area: parseInt(1), department: 'Misc', weight: null, active: true },
        { number: 32, name: 'Pillowcase', standard: parseInt(400), area: parseInt(2), department: 'SP Iron', weight: null, active: true },
        { number: 33, name: 'Mixed Towels', standard: parseInt(680), area: parseInt(1), department: 'Towels', weight: parseInt(1), active: true },
		{ number: 36, name: 'Scrub Top', standard: parseInt(225), area: parseInt(2), department: 'SP Iron', weight: parseInt(1), active: true },
		{ number: 37, name: 'Scrub Pants', standard: parseInt(225), area: parseInt(2), department: 'SP Iron', weight: parseInt(1), active: true },
        { number: 38, name: 'Baby Blanket', standard: parseInt(600), area: parseInt(1), department: 'Baby Items', weight: null, active: true },
        { number: 39, name: 'Bath Towel (one size)', standard: parseInt(680), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 40, name: 'MIX-2 French', standard: parseInt(680), area: parseInt(1), department: 'Towels', weight: null, active: true },
        { number: 41, name: 'Yell/Mist Gowns', standard: parseInt(360), area: parseInt(1), department: 'Towels', weight: null, active: true }
    ]*/
}