module.exports = {
	item: [
		{"number":1,"name":"Incontinent Pad","pace":720,"area":"1","department":"Towels","weight":null},
		{"number":2,"name":"Bath Mat","pace":720,"area":"1","department":"Towels","weight":null},
		{"number":3,"name":"Patient Gown","pace":400,"area":"1","department":"Towels","weight":null},
		{"number":4,"name":"Pool Towel","pace":625,"area":"1","department":"Towels","weight":null},
		{"number":5,"name":"Bath Towel","pace":625,"area":"1","department":"Towels","weight":null},
		{"number":6,"name":"Hand Towel","pace":625,"area":"1","department":"Towels","weight":null},
		{"number":7,"name":"Bath Towel (1Primary)","pace":625,"area":"1","department":"Towels","weight":null},
		{"number":8,"name":"Hand Towel (1Primary)","pace":625,"area":"1","department":"Towels","weight":null},
		{"number":9,"name":"Bib White (Sideway)","pace":625,"area":"1","department":"Hand Work","weight":null},
		{"number":10,"name":"Bib color (Longway)","pace":625,"area":"1","department":"Hand Work","weight":null},
		{"number":11,"name":"Bib color (Small)","pace":600,"area":"15","department":"Hand Work","weight":null},
		{"number":12,"name":"Patient Gown XL Grand","pace":360,"area":"1","department":"Towels","weight":null},
		{"number":13,"name":"Thermal Blanket","pace":480,"area":"1","department":"Blankets","weight":null},
		{"number":14,"name":"Bath Sheet","pace":600,"area":"1","department":"Sheets","weight":null},
		{"number":15,"name":"Bath Blanket","pace":480,"area":"1","department":"Blankets","weight":null},
		{"number":16,"name":"Towel (1Primary)","pace":625,"area":"1","department":"Towels","weight":null},
		{"number":17,"name":"Blankets","pace":480,"area":"1","department":"Blankets","weight":null},
		{"number":18,"name":"Pads","pace":720,"area":"1","department":"Hand Work","weight":null},
		{"number":19,"name":"Fitted Sheets","pace":360,"area":"2","department":"Sheets","weight":null},
		{"number":21,"name":"Quilted Blanket","pace":300,"area":"1","department":"Blankets","weight":null},
		{"number":20,"name":"Fitted Sheets Large","pace":300,"area":"1","department":"Sheets","weight":null},
		{"number":22,"name":"Knitted Fitted (offset L)","pace":330,"area":"1","department":"Sheets","weight":null},
		{"number":23,"name":"WashCloth","pace":1425,"area":"1","department":"Hand Work","weight":null},
		{"number":24,"name":"BarMop","pace":1380,"area":"1","department":"Misc","weight":null},
		{"number":25,"name":"Knitted Fitted","pace":330,"area":"1","department":"Sheets","weight":null},
		{"number":26,"name":"HospitalSheet","pace":375,"area":"2","department":"Sheets","weight":null},
		{"number":27,"name":"Table Linen","pace":300,"area":"2","department":"Table Tops","weight":null},
		{"number":28,"name":"Wash Cloth","pace":1380,"area":"1","department":"Hand Work","weight":null},
		{"number":29,"name":"Hotel Sheet","pace":420,"area":"2","department":"Sheets","weight":null},
		{"number":30,"name":"Large Thermal Blanket","pace":480,"area":"2","department":"Blankets","weight":null},
		{"number":31,"name":"Large Blanket","pace":480,"area":"2","department":"Blankets","weight":null},
		{"number":0,"name":"Needs To Be Added ","pace":750,"area":"1","department":"Misc","weight":null},
		{"number":32,"name":"Pillowcase","pace":400,"area":"2","department":"SP Iron","weight":null},
		{"number":33,"name":"Mixed Towels","pace":680,"area":"1","department":"Towels","weight":1},
		{"number":36,"name":"Scrub Top","pace":225,"area":"2","department":"SP Iron","weight":1},
		{"number":37,"name":"Scrub Pants","pace":225,"area":"2","department":"SP Iron","weight":1},
		{"number":38,"name":"Baby Blanket","pace":600,"area":"1","department":"Baby Items","weight":null},
		{"number":39,"name":"Bath Towel (one size)","pace":680,"area":"1","department":"Towels","weight":null},
		{"number":40,"name":"MIX-2 French","pace":680,"area":"1","department":"Towels","weight":null},
		{"number":41,"name":"Yell/Mist Gowns","pace":360,"area":"1","department":"Towels","weight":null}
		]
}