module.exports = {
	status: [
		{ "code": 0, "name": "Timeout", "jam": 3, softrolColor: 'Grey' },
		{ "code": 1, "name": "Run", "jam": 0, softrolColor: 'Green' },
		{ "code": 2, "name": "Stop", "jam": 2, softrolColor: 'Red' },
		{ "code": 3, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 4, "name": "Waiting", "jam": 3, softrolColor: 'Amber' },
		{ "code": 5, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 6, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 7, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 8, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 9, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 10, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 11, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 12, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 13, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 14, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 15, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 16, "name": "Estop/Door", "jam": 2, softrolColor: 'Red' },
		{ "code": 17, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 18, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 19, "name": "Lo Air Pressure", "jam": 0, softrolColor: 'Red' },
		{ "code": 20, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 21, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 22, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 23, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 24, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 25, "name": "Lo Air Pressure", "jam": 0, softrolColor: 'Red' },
		{ "code": 26, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 27, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 28, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 29, "name": "Fault", "jam": 0, softrolColor: 'Red' },
		{ "code": 30, "name": "Jam @Primary", "jam": 1, softrolColor: 'Red' },
		{ "code": 31, "name": "Jam @Cross1", "jam": 1, softrolColor: 'Red' },
		{ "code": 32, "name": "Jam @Cross2", "jam": 1, softrolColor: 'Red' },
		{ "code": 33, "name": "Jam @Stacker", "jam": 1, softrolColor: 'Red' },
		{ "code": 34, "name": "Jam @Cross1", "jam": 1, softrolColor: 'Red' },
		{ "code": 35, "name": "Jam@Cross2", "jam": 1, softrolColor: 'Red' },
		{ "code": 36, "name": "Jam @Cross3/Exit", "jam": 1, softrolColor: 'Red' },
		{ "code": 37, "name": "Jam @Cross3/Exit", "jam": 1, softrolColor: 'Red' },
		{ "code": 38, "name": "Jam @Cross3/Exit", "jam": 1, softrolColor: 'Red' },
		{ "code": 39, "name": "Jam @Cross3/Exit", "jam": 1, softrolColor: 'Red' },
		{ "code": 100, "name": "Pause @Feeder ", "jam": 3, softrolColor: 'Amber' },
		{ "code": 131, "name": "Feeder Left Inlet Jam ", "jam": 1, softrolColor: 'Red' },
		{ "code": 102, "name": "Feeder Stop", "jam": 2, softrolColor: 'Red' },
		{ "code": -1, "name": "Offline", "jam": 0, softrolColor: 'Grey' },
		{ "code": 141, "name": "Feeder Right Inlet Jam", "jam": 1, softrolColor: 'Red' },
		{ "code": 171, "name": "Feeder Servo Fault", "jam": 1, softrolColor: 'Red' },
		{ "code": 173, "name": "Feeder Wall Jam", "jam": 1, softrolColor: 'Red' },
		{ "code": 152, "name": "Feeder Inlet Jam", "jam": 1, softrolColor: 'Red' },
		{ "code": 153, "name": "Feeder Inlet Jam", "jam": 1, softrolColor: 'Red' },
		{ "code": 174, "name": "Feeder Tail Sensor Jam", "jam": 1, softrolColor: 'Red' },
		{ "code": 175, "name": "Feeder Spreader Home Failure", "jam": 1, softrolColor: 'Red' },
		{ "code": 103, "name": "Ironer Stopped", "jam": 2, softrolColor: 'Red' },
		{ "code": 114, "name": "Feeder Estop", "jam": 2, softrolColor: 'Red' },
		{ "code": 124, "name": "Feeder Estop/Reset", "jam": 2, softrolColor: 'Red' },
		{ "code": 181, "name": "Feeder Center Inlet Jam ", "jam": 1, softrolColor: 'Red' },
		{ "code": 151, "name": "Feeder Transverse Left Drive ", "jam": 1, softrolColor: 'Red' },
		{ "code": 161, "name": "Feeder Transverse Right Drive", "jam": 1, softrolColor: 'Red' },
		{ "code": 184, "name": "Feeder Rollmotor Fault Center", "jam": 1, softrolColor: 'Red' },
		{ "code": 185, "name": "Feeder Center Inlet Sensor ", "jam": 1, softrolColor: 'Red' },
		{ "code": 186, "name": "Feeder Center Inlet Left Array  ", "jam": 1, softrolColor: 'Red' },
		{ "code": 187, "name": "Feeder Center Inlet Right Array ", "jam": 1, softrolColor: 'Red' },
		{ "code": 188, "name": "Feeder Center Inlet Left RollSensor", "jam": 1, softrolColor: 'Red' },
		{ "code": 189, "name": "Feeder Center Inlet Right RollSensor", "jam": 1, softrolColor: 'Red' },
		{ "code": 134, "name": "Feeder Rollmotor Fault Left", "jam": 1, softrolColor: 'Red' },
		{ "code": 135, "name": "Feeder Left Inlet Sensor ", "jam": 1, softrolColor: 'Red' },
		{ "code": 136, "name": "Feeder Left Inlet Left Array  ", "jam": 1, softrolColor: 'Red' },
		{ "code": 137, "name": "Feeder Left Inlet Right Array  ", "jam": 1, softrolColor: 'Red' },
		{ "code": 138, "name": "Feeder Left Inlet Left RollSensor", "jam": 1, softrolColor: 'Red' },
		{ "code": 139, "name": "Feeder Left Inlet Right RollSensor", "jam": 1, softrolColor: 'Red' },
		{ "code": 144, "name": "Feeder Rollmotor Fault Right", "jam": 1, softrolColor: 'Red' },
		{ "code": 145, "name": "Feeder Right Inlet Sensor ", "jam": 1, softrolColor: 'Red' },
		{ "code": 146, "name": "Feeder Right Inlet Left Array  ", "jam": 1, softrolColor: 'Red' },
		{ "code": 147, "name": "Feeder Right Inlet Right Array  ", "jam": 1, softrolColor: 'Red' },
		{ "code": 148, "name": "Feeder Right Inlet Left RollSensor", "jam": 1, softrolColor: 'Red' },
		{ "code": 149, "name": "Feeder Right Inlet Right RollSensor", "jam": 1, softrolColor: 'Red' },
		{ "code": 112, "name": "Feeder Estop", "jam": 2, softrolColor: 'Red' },
		{ "code": 113, "name": "Feeder Estop", "jam": 2, softrolColor: 'Red' },
		{ "code": 130, "name": "Inverter Fault Ironer", "jam": 2, softrolColor: 'Red' },
		{ "code": 122, "name": "Feeder Estop Reset", "jam": 2, softrolColor: 'Red' },
		{ "code": 125, "name": "Inverter Fault Feeder", "jam": 1, softrolColor: 'Red' },
		{ "code": 155, "name": "Feeder Left Transverse Sensor Fault", "jam": 1, softrolColor: 'Red' },
		{ "code": 165, "name": "Feeder Right Transverse Sensor Fault", "jam": 1, softrolColor: 'Red' }
		]
}