import { Routes } from '@angular/router';
import { ConfigGridTestComponent } from './config-grid-test/config-grid-test.component';
//import { SettingsOperatorsComponent } from './settings-operators/settings-operators.component';
import { OperatorGridComponent } from './operator-grid/operator-grid.component';
import { ItemGridComponent } from './item-grid/item-grid.component';
import { UserLoginComponent } from './user-login/user-login.component';
import { UserRegisterComponent } from './user-register/user-register.component';
import { LeveloneDashboardComponent } from './levelone-dashboard/levelone-dashboard.component';
import { LeveloneTableComponent } from './levelone-table/levelone-table.component';
import { LeveloneTableV2Component } from './levelone-table-v2/levelone-table-v2.component';
import { LeveloneBarChartComponent } from './levelone-bar-chart/levelone-bar-chart.component';
import { LevelonePieChartComponent } from './levelone-pie-chart/levelone-pie-chart.component';
import { LeveloneLineChartComponent } from './levelone-line-chart/levelone-line-chart.component';
import { MachineAnalyticsDashboardComponent } from './machine-analytics-dashboard/machine-analytics-dashboard.component';
import { MachineAnalyticsChartComponent } from './machine-analytics-chart/machine-analytics-chart.component';
import { OperatorAnalyticsDashboardComponent } from './operator-analytics-dashboard/operator-analytics-dashboard.component';
import { OperatorPerformanceChartComponent } from './operator-performance-chart/operator-performance-chart.component';
import { UseModalComponent } from './use-modal/use-modal.component';
import { OperatorCountbyitemChartComponent } from './operator-countbyitem-chart/operator-countbyitem-chart.component';
import { MachineFaultHistoryComponent } from './machine-fault-history/machine-fault-history.component';
import { DailySummaryDashboardComponent } from './daily-summary-dashboard/daily-summary-dashboard.component';
import { ItemAnalyticsDashboardComponent } from './item-analytics-dashboard/item-analytics-dashboard.component';
import { AuthGuard } from './guards/auth.guard';
import { TestComponent } from './test/test.component';
import { DailyAnalyticsDashboardComponent } from './daily-analytics-dashboard/daily-analytics-dashboard.component';
import { MachineDashboardComponent } from './machine-dashboard/machine-dashboard.component';
import { MachineReportComponent } from './reports/machine-report/machine-report.component';
import { OperatorReportComponent } from './reports/operator-report/operator-report.component';
import { ItemReportComponent } from './reports/item-report/item-report.component';
import { AC360SixLaneComponent } from './ac360-six-lane/ac360-six-lane.component';
import { BlanketBlasterone } from './blanket-blasterone/blanket-blasterone';
import { BlanketBlastertwo } from './blanket-blastertwo/blanket-blastertwo';
import { MachineGridComponent } from './machine-grid/machine-grid.component';
import { EfficiencyScreens } from './efficiency-screens/efficiency-screens.component';
import { SplEfficiencyScreen } from './efficiency-screens/spl-efficiency-screen/spl-efficiecny-screen.component';

export const routes: Routes = [
	{ path: 'ng/configGridTest', component: ConfigGridTestComponent },
	{ path: 'ng/settings/operators', component: OperatorGridComponent },
	{ path: 'ng/settings/items', component: ItemGridComponent,},
	{ path: 'ng/settings/machines', component: MachineGridComponent,  },
	{ path: 'ng/settings/root/users/register', component: UserRegisterComponent, canActivate: [AuthGuard] },
	{ path: 'ng/login', component: UserLoginComponent },
	{ path: 'ng/home', component: LeveloneDashboardComponent },
	{ path: 'ng/levelone-table', component: LeveloneTableComponent },
	{ path: 'ng/levelone-table-v2', component: LeveloneTableV2Component },
	{ path: 'ng/levelone-bar-chart', component: LeveloneBarChartComponent },
	{ path: 'ng/levelone-pie-chart', component: LevelonePieChartComponent },
	{ path: 'ng/levelone-line-chart', component: LeveloneLineChartComponent },
	{ path: 'ng/machineAnalytics', component: MachineAnalyticsDashboardComponent },
	{ path: 'ng/machineAnalytics/chart', component: MachineAnalyticsChartComponent },
	{ path: 'ng/operatorAnalytics', component: OperatorAnalyticsDashboardComponent },
	{ path: 'ng/operator-performance-chart', component: OperatorPerformanceChartComponent },
	{ path: 'ng/use-modal', component: UseModalComponent },
	{ path: 'ng/operator-countbyitem', component: OperatorCountbyitemChartComponent },
	{ path: 'ng/machine-fault-history', component: MachineFaultHistoryComponent },
	{ path: 'ng/daily-summary', component: DailySummaryDashboardComponent },
	{ path: 'ng/itemAnalytics', component: ItemAnalyticsDashboardComponent },
	{ path: 'ng/test', component: TestComponent },
	{ path: 'ng/daily-analytics', component: DailyAnalyticsDashboardComponent },
	{ path: 'ng/analytics/machine-dashboard', component: MachineDashboardComponent },
	{ path: 'ng/reports/machine-report', component: MachineReportComponent },
	{ path: 'ng/reports/operator-report', component: OperatorReportComponent },
	{ path: 'ng/reports/item-report', component: ItemReportComponent },	
	{ path: 'ng/ac360-six-lane', component: AC360SixLaneComponent },
	{ path: 'ng/blanket-blaster-one', component: BlanketBlasterone },
	{ path: 'ng/blanket-blaster-two', component: BlanketBlastertwo },
	{ path: 'ng/efficiency-screens', component: EfficiencyScreens },
	{ path: 'ng/spl-efficiency-screen', component: SplEfficiencyScreen },
	{ path: 'ng/*', redirectTo: 'ng/home' }
	];
